wandb_version: 1

env_name:
  desc: null
  value: humanoid_mjx
algo_name:
  desc: null
  value: ppo
task_name:
  desc: null
  value: run
num_envs:
  desc: null
  value: 5
num_timesteps:
  desc: null
  value: 1000
eval_every:
  desc: null
  value: 100
episode_length:
  desc: null
  value: 500
num_evals:
  desc: null
  value: 1000
batch_size:
  desc: null
  value: 4
learning_rate:
  desc: null
  value: 0.0006
terminate_when_unhealthy:
  desc: null
  value: false
run_platform:
  desc: null
  value: local
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706294385.538077
    t:
      1:
      - 12
      - 45
      - 55
      2:
      - 12
      - 45
      - 55
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.10.9
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
